language: c
compiler:
  - gcc
  - clang
env:
  -
  - SANITIZE=address
  - SANITIZE=undefined
matrix:
  exclude:
    - compiler: gcc
      env: SANITIZE=address
    - compiler: gcc
      env: SANITIZE=undefined
  allow_failures:
    - compiler: clang
      env: SANITIZE=address
    - compiler: clang
      env: SANITIZE=undefined
before_install:
  - sudo apt-get install libprotobuf-c0-dev libprotobuf-c0 protobuf-c-compiler
  - sudo apt-get install libjansson-dev libjansson4
install: ./autogen.sh && ./configure && make
script:
  - make test
  - make benchmark
