language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install libprotobuf-c0-dev libprotobuf-c0 protobuf-c-compiler
  - sudo apt-get install libjansson-dev libjansson4
install: ./autogen.sh && ./configure && make
script:
  - make test
  - make benchmark
